export enum QueueProcessingStrategyType {
  RETRY_ALL = 'RETRY_ALL',
  RETRY_FAILED = 'RETRY_FAILED',
  RETRY_FAILED_AND_TIMED_OUT = 'RETRY_FAILED_AND_TIMED_OUT',
  RETRY_TIMED_OUT = 'RETRY_TIMED_OUT',
  SKIP_ALL_FAILURES = 'SKIP_ALL_FAILURES',
  SKIP_ALL_FAILURES_AND_TIMED_OUT = 'SKIP_ALL_FAILURES_AND_TIMED_OUT',
}

export enum QueueServiceType {
  JS_EXECUTOR = 'JS_EXECUTOR',
  TB_CORE = 'TB_CORE',
  TB_RULE_ENGINE = 'TB_RULE_ENGINE',
  TB_TRANSPORT = 'TB_TRANSPORT',
  TB_VC_EXECUTOR = 'TB_VC_EXECUTOR',
}

export enum QueueSubmitStrategyType {
  BATCH = 'BATCH',
  BURST = 'BURST',
  SEQUENTIAL = 'SEQUENTIAL',
  SEQUENTIAL_BY_ORIGINATOR = 'SEQUENTIAL_BY_ORIGINATOR',
  SEQUENTIAL_BY_TENANT = 'SEQUENTIAL_BY_TENANT',
}
