export enum WsCmdType {
  NOTIFICATIONS_COUNT = 'NOTIFICATIONS_COUNT',
  NOTIFICATIONS = 'NOTIFICATIONS',
  MARK_ALL_NOTIFICATIONS_AS_READ = 'MARK_ALL_NOTIFICATIONS_AS_READ',
  TIMESERIES = 'TIMESERIES',
  ATTRIBUTES = 'ATTRIBUTES',
  ENTITY_DATA = 'ENTITY_DATA',
  ENTITY_DATA_UNSUBSCRIBE = 'ENTITY_DATA_UNSUBSCRIBE',
}
