export enum WsCmdType {
  ENTITY_COUNT = 'ENTITY_COUNT',
  ENTITY_COUNT_UNSUBSCRIBE = 'ENTITY_COUNT_UNSUBSCRIBE',
  ALARM_COUNT = 'ALARM_COUNT',
  ALARM_COUNT_UNSUBSCRIBE = 'ALARM_COUNT_UNSUBSCRIBE',
  NOTIFICATIONS_COUNT = 'NOTIFICATIONS_COUNT',
  NOTIFICATIONS = 'NOTIFICATIONS',
  MARK_ALL_NOTIFICATIONS_AS_READ = 'MARK_ALL_NOTIFICATIONS_AS_READ',
  TIMESERIES = 'TIMESERIES',
  ATTRIBUTES = 'ATTRIBUTES',
  ENTITY_DATA = 'ENTITY_DATA',
  ENTITY_DATA_UNSUBSCRIBE = 'ENTITY_DATA_UNSUBSCRIBE',
}
