export enum WsCmdType {
  ATTRIBUTES = 'ATTRIBUTES',
  ENTITY_DATA = 'ENTITY_DATA',
  ENTITY_DATA_UNSUBSCRIBE = 'ENTITY_DATA_UNSUBSCRIBE',
  MARK_ALL_NOTIFICATIONS_AS_READ = 'MARK_ALL_NOTIFICATIONS_AS_READ',
  NOTIFICATIONS = 'NOTIFICATIONS',
  NOTIFICATIONS_COUNT = 'NOTIFICATIONS_COUNT',
  TIMESERIES = 'TIMESERIES',
}
