export enum RelationTypeGroup {
  COMMON = 'COMMON',
  DASHBOARD = 'DASHBOARD',
  EDGE = 'EDGE',
  EDGE_AUTO_ASSIGN_RULE_CHAIN = 'EDGE_AUTO_ASSIGN_RULE_CHAIN',
  RULE_CHAIN = 'RULE_CHAIN',
  RULE_NODE = 'RULE_NODE',
}
